import { formatDateTime, formatDate } from '../../utils/format';
import { PrintShell, ClinicHeader, PrintFieldGrid, PrintRow } from './PrintShell';

export function ConsultationPrint({ consultation, visit, patient, onClose }) {
  const v = consultation?.vitals || {};
  const vitalsRows = [
    ['Blood Pressure', v.bloodPressure ? `${v.bloodPressure} mmHg` : ''],
    ['Pulse', v.pulse ? `${v.pulse} bpm` : ''],
    ['Temperature', v.temperature ? `${v.temperature} °C` : ''],
    ['Respiratory Rate', v.respiratoryRate ? `${v.respiratoryRate} /min` : ''],
    ['Weight', v.weight ? `${v.weight} kg` : ''],
    ['Height', v.height ? `${v.height} cm` : ''],
  ];

  const sections = [
    ['Chief Complaint', consultation?.chiefComplaint],
    ['Medical History', consultation?.medicalHistory],
    ['Clinical Examination', consultation?.clinicalExamination],
    ['Diagnosis', consultation?.diagnosis],
    ['Treatment Recommendation', consultation?.treatmentRecommendation],
    ["Doctor's Notes", consultation?.doctorNotes],
    ['Follow-up', consultation?.followUp],
    ['Referral', consultation?.referral],
  ];

  return (
    <PrintShell title="Consultation Record" onClose={onClose} printLabel="Print Record">
      <ClinicHeader title="CONSULTATION RECORD" />

      <div className="mb-5 rounded-lg border border-slate-200 bg-slate-50 p-4">
        <PrintFieldGrid
          patient={patient}
          extra={[
            ['Visit Number', visit?.visitNumber],
            ['Consultation No.', consultation?.consultationNumber],
            ['Doctor', consultation?.doctor],
            ['Service', visit?.service],
            ['Date', formatDateTime(consultation?.date)],
          ]}
        />
      </div>

      <h3 className="mb-2 text-sm font-bold uppercase tracking-wide text-slate-500">Vital Signs</h3>
      <div className="mb-6 grid grid-cols-2 gap-x-8 gap-y-1.5 rounded-lg border border-slate-200 p-4 sm:grid-cols-3">
        {vitalsRows.map(([label, value]) => (
          <PrintRow key={label} label={label} value={value} bold />
        ))}
      </div>

      <h3 className="mb-2 text-sm font-bold uppercase tracking-wide text-slate-500">Clinical Assessment</h3>
      <div className="space-y-4">
        {sections.map(([label, value]) => (
          <div key={label}>
            <p className="text-xs font-semibold text-slate-500">{label}</p>
            <p className="mt-0.5 whitespace-pre-wrap text-sm text-slate-800">{value || '—'}</p>
          </div>
        ))}
      </div>

      <div className="mt-8 flex items-end justify-between">
        <p className="max-w-sm text-xs italic text-slate-400">
          This consultation record was generated by the St. Michael Medium Clinic patient management system.
        </p>
        <div className="text-right">
          <p className="text-xs font-semibold text-slate-500">Attending Doctor</p>
          <p className="mt-4 text-sm font-semibold text-slate-800">{consultation?.doctor || '—'}</p>
          <p className="text-xs text-slate-400">{formatDate(consultation?.date)}</p>
        </div>
      </div>
    </PrintShell>
  );
}
