import { useTranslation } from 'react-i18next';
import { formatDateTime, formatDate } from '../../utils/format';
import { PrintShell, ClinicHeader, PrintFieldGrid, PrintRow } from './PrintShell';

const CLINIC_NAME = 'St. Michael Medium Clinic';

export function LabResultPrint({ request, result, onClose }) {
  const { t } = useTranslation();
  const patient = request?.patient || {
    fullName: request?.patientName,
    id: request?.patientId,
  };

  return (
    <PrintShell title="Laboratory Result" onClose={onClose} printLabel="Print Result">
      <ClinicHeader title="LABORATORY RESULT" />

      <div className="mb-5 rounded-lg border border-slate-200 bg-slate-50 p-4">
        <PrintFieldGrid
          patient={patient}
          extra={[
            ['Visit Number', request?.visitNumber],
            ['Request Number', request?.requestNumber],
            ['Requesting Doctor', request?.requestingDoctor],
            ['Sample Date', formatDateTime(request?.date)],
          ]}
        />
      </div>

      <table className="w-full border-collapse text-sm">
        <thead>
          <tr className="bg-brand-50 text-left">
            <th className="border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">{t('Test')}</th>
            <th className="border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">{t('Result')}</th>
            <th className="border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">{t('Unit')}</th>
            <th className="border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">{t('Reference Range')}</th>
            <th className="border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">{t('Remarks')}</th>
          </tr>
        </thead>
        <tbody>
          {(result?.results || []).map((r) => (
            <tr key={r.testId}>
              <td className="border border-slate-200 px-3 py-2 font-medium text-slate-800">{r.testName}</td>
              <td className="border border-slate-200 px-3 py-2 font-semibold text-slate-800">{r.result || '—'}</td>
              <td className="border border-slate-200 px-3 py-2 text-slate-600">{r.unit}</td>
              <td className="border border-slate-200 px-3 py-2 text-slate-600">{r.referenceRange}</td>
              <td className="border border-slate-200 px-3 py-2 text-slate-600">{r.remarks || '—'}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mt-8 grid grid-cols-2 gap-6">
        <div>
          <p className="text-xs font-semibold text-slate-500">{t('Result Entered By')}</p>
          <p className="text-sm font-medium text-slate-700">{result?.enteredBy || '—'}</p>
          <p className="text-xs text-slate-400">{result?.enteredAt ? formatDateTime(result.enteredAt) : ''}</p>
        </div>
        <div>
          <p className="text-xs font-semibold text-slate-500">{t('Result Verified By')}</p>
          <p className="text-sm font-medium text-slate-700">{result?.verifiedBy || '—'}</p>
          <p className="text-xs text-slate-400">{result?.verifiedAt ? formatDateTime(result.verifiedAt) : ''}</p>
        </div>
      </div>

      <p className="mt-8 text-center text-[10px] text-slate-400">
        {t('This result was generated by')} {t(CLINIC_NAME)} {t('on')} {formatDate(new Date().toISOString())}. {t('Please consult your doctor for interpretation.')}
      </p>
    </PrintShell>
  );
}
