import { useTranslation } from 'react-i18next';
import { formatDate, formatDateTime } from '../../utils/format';
import { PrintShell, ClinicHeader, PrintFieldGrid, PrintRow } from './PrintShell';

export function PatientVisitPrint({ visit, patient, onClose }) {
  const { t } = useTranslation();
  return (
    <PrintShell title="Patient / Visit Information" onClose={onClose} printLabel="Print">
      <ClinicHeader title="PATIENT / VISIT" />

      <div className="mb-5 rounded-lg border border-slate-200 bg-slate-50 p-4">
        <PrintFieldGrid
          patient={patient}
          extra={[
            ['Visit Number', visit?.visitNumber],
            ['Service', visit?.service],
            ['Reason', visit?.reason],
            ['Date & Time', formatDateTime(visit?.date)],
          ]}
        />
      </div>

      <div className="grid gap-2 text-sm">
        <PrintRow label="Visit Status" value={t(visit?.status || '')} />
        <PrintRow label="Registered On" value={formatDate(patient?.registrationDate)} />
        <PrintRow label="Phone" value={patient?.phone} />
        <PrintRow label="Address" value={patient?.address} />
      </div>

      <p className="mt-8 text-center text-[10px] text-slate-400">
        {t('Generated by')} {t('St. Michael Medium Clinic')} {t('on')} {formatDate(new Date().toISOString())}.
      </p>
    </PrintShell>
  );
}
